# site settings
title: Onyi Lam
subtitle: My net presence
email: onyilam@gmail.com
description: Computational Social Scientist. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "onyilam.github.io" # the base hostname & protocol for your site
author:
street_address:
city: Washington
state: DC
zip_code:
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/onyilam
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/onyilam

# build settings
markdown: kramdown

sass:
  style: compressed
